apiVersion: v1
kind: ServiceAccount
metadata:
  name: skin-lesion-backend
  namespace: skin-lesion-dev
  annotations:
    eks.amazonaws.com/role-arn: "REPLACE_WITH_TERRAFORM_OUTPUT_dsql_workload_role_arn"
