services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.19.0
    container_name: skin-lesion-mlflow-local
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --default-artifact-root /mlflow/artifacts
    ports:
      - "5000:5000"
    volumes:
      - skin_lesion_mlflow_data:/mlflow

volumes:
  skin_lesion_mlflow_data:
