apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: skin-lesion-backend
  namespace: skin-lesion-prod
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: skin-lesion-backend
